"""Add Stats Table

Revision ID: 1bfc808a2677
Revises: dc942e1e7bef
Create Date: 2018-07-30 22:07:06.399421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfc808a2677'
down_revision = 'dc942e1e7bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player__game__stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('dropbacks', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('aimed', sa.Integer(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('passing_yds', sa.Integer(), nullable=True),
    sa.Column('passing_tds', sa.Integer(), nullable=True),
    sa.Column('passing_adot', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('sacks', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('adjusted_completion_percentage', sa.Float(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('rushing_yards', sa.Integer(), nullable=True),
    sa.Column('rushing_tds', sa.Integer(), nullable=True),
    sa.Column('rushing_fumbles', sa.Integer(), nullable=True),
    sa.Column('yds_per_carry', sa.Float(), nullable=True),
    sa.Column('yds_after_contact', sa.Float(), nullable=True),
    sa.Column('tackles_avoided', sa.Integer(), nullable=True),
    sa.Column('tackles_avoided_per_attempt', sa.Float(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('receiving_yds', sa.Integer(), nullable=True),
    sa.Column('receiving_tds', sa.Integer(), nullable=True),
    sa.Column('receiving_fumbles', sa.Integer(), nullable=True),
    sa.Column('receiving_adot', sa.Float(), nullable=True),
    sa.Column('drops', sa.Integer(), nullable=True),
    sa.Column('catch_percentage', sa.Float(), nullable=True),
    sa.Column('yds_per_reception', sa.Float(), nullable=True),
    sa.Column('yds_per_target', sa.Float(), nullable=True),
    sa.Column('receiving_yds_after_catch', sa.Float(), nullable=True),
    sa.Column('fantasy_points_standard', sa.Integer(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player__game__stats_player_id'), 'player__game__stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player__game__stats_player_id'), table_name='player__game__stats')
    op.drop_table('player__game__stats')
    # ### end Alembic commands ###
